### ISSUE TITLE
Main README

### ISSUE THREAD

**Issue by dominicm00** [dominicm00/ham#1]
Tracker issue for main README

- [ ] Introduction
WIP disclaimer. What is Ham, links to Perforce/Boost Jam.
- [ ] Motivation:
Why create Ham? Talk about:
- Multi-threading bugs
- Cache issues
- Not usable as a library
- [ ] Progress:
Currently a work in progress and not usable. Link to 1.0 tracker.
- [ ] Usage:
Link to the Jam documentation. Document Ham-specific features such as compatibility modes.
- [ ] Building:
Building either with an existing Jam/Ham installation, or using Bootstrap.sh

**Comment by stippi** [comment]
As long as Ham does not have it's own *user* documentation, perhaps linking to general Jam documentation is a good idea. For example, this is a nice introduction: http://geoz.co.nz/jamdoc/jam-guide.html

**Comment by dominicm00** [comment]
That link is dead for me, but I was going to link to the [Perforce documentation](https://swarm.workshop.perforce.com/view/guest/perforce_software/jam/src/Jam.html) and just document additional features Ham has like compatibility modes.

**Comment by stippi** [comment]
Sorry about that... https://web.archive.org/web/20160304233139/http://geoz.co.nz/jamdoc/jam-guide.html

**Comment by dominicm00** [comment]
Thank you; that's a nice user friendly guide to have 😄
