### ISSUE TITLE
Use C++20 formatters

### ISSUE THREAD

**Issue by dominicm00** [dominicm00/ham#132]
C++20 formatters are a nice alternative to streams, especially as we begin to use more complex terminal output. However, they currently do not have good compiler support so we cannot use it.

Once formatters are more widespread, consider switching implementations of `operator<<` and `.String()` to formatter specializations.

**Comment by nielx** [comment]
I suspect that you probably want to reduce the number of external dependencies, but [fmt](https://github.com/fmtlib/fmt) is a great library.

**Comment by dominicm00** [comment]
> I suspect that you probably want to reduce the number of external dependencies, but [fmt](https://github.com/fmtlib/fmt) is a great library.

Yeah, fmt is compatible with C++20 format (I believe it inspired it?), so it will be fairly trivial to port to C++20 format. Right now though Ham's output is very minimal since I'm focusing on the interpreter functionality, but once I can focus on prettier/more complete output I'll likely use this until C++20 has better support.

**Comment by dominicm00** [comment]
Ham v2 has been moved; closing issues not relevant for v1.
