### ISSUE TITLE
Replace custom string code with standard library.

### ISSUE THREAD

**Issue by dominicm00** [dominicm00/ham#15]
Ham's data is made of lists of strings, which are handled manually for the sake of efficiency (see `src/String*`). However, C++17 [string views](https://en.cppreference.com/w/cpp/string/basic_string_view) and C++20 [ranges](https://en.cppreference.com/w/cpp/ranges) allow for safer, and still efficient, handling of string/list data. 

The `src/String*` code should be removed, and the rest of the codebase should rely on standard library types.

**Comment by stippi** [comment]
In the HaikuDepot source code, something similar was done to replace the custom List.h template code with `std::` containers. While I agree that it's a good idea to replace the actual implementation with a proven `std::` one, I am not a fan of replacing the custom API. In the HaikuDepot case, the STL API was so verbose, that the code was blown up and obfuscated. But not only that, the API was so unintuitive that bugs were introduced while doing something trivial like removing an item from the list.

**Comment by dominicm00** [comment]
Hmm, so wrap all the STL types so that I can adjust the functionality? That seems reasonable, especially with all the operations Ham needs to do on strings. Would it make sense as a general guideline to use the STL types for one-off use cases, and wrap common data types with custom classes?

**Comment by nielx** [comment]
> Hmm, so wrap all the STL types so that I can adjust the functionality? That seems reasonable, especially with all the operations Ham needs to do on strings. Would it make sense as a general guideline to use the STL types for one-off use cases, and wrap common data types with custom classes?

I think it is better to be pragmatic. I have had a quick skim over the source, and it seems that these standard types are pretty vanilla, and you can do the same with the standard library. So I would definitely not go as far as to have the basic approach of keeping the custom classes but changing the guts. If you start with replacing the container classes, you will quickly find out how the rest is going to go.

**Comment by nielx** [comment]
Having said that, it is interesting to find out why Ingo chose to implement a custom String class in a C++14 codebase.

**Comment by dominicm00** [comment]
> I think it is better to be pragmatic. I have had a quick skim over the source, and it seems that these standard types are pretty vanilla, and you can do the same with the standard library. So I would definitely not go as far as to have the basic approach of keeping the custom classes but changing the guts. If you start with replacing the container classes, you will quickly find out how the rest is going to go.

Ok; do you think it would make more sense to have common operations as functions that take in a standard type, rather than trying to wrap all the functionality? For example, instead of having `string_list.join("-")` you would have `data::JoinStringList(string_list, "-")`. This might make more sense than trying to forward all the STL functionality.

**Comment by dominicm00** [comment]
> Having said that, it is interesting to find out why Ingo chose to implement a custom String class in a C++14 codebase.

I don't know why he created `String`, but it seems to be some weird holdover and isn't used anywhere. The class that's used is `StringBuffer`, which is just a wrapper for `std::string`. The rest of the custom string/list code though is necessary to access substrings/sublists without copying, as string views and ranges are only available in C++17 and C++20 respectively.
